### ISSUE TITLE
Inconsistency between Matrix3f and Matrix4f

### ISSUE THREAD

**Issue by Hermasetas** [JOML-CI/JOML#167] opened 2018-07-30 19:12 UTC
The values of a Matrix3f is visible, and they are not for a Matrix4f.

Example:
`Matrix3f.m00` is accesible.
`Matrix4f.m00` is not accesible and one must use `Matrix4f.m00()`

Version 1.9.10

**Comment by httpdigest** [comment] 2018-07-30 19:19
Duplicate of https://github.com/JOML-CI/JOML/issues/156, https://github.com/JOML-CI/JOML/issues/130

**Closed** 2018-07-30 19:19 UTC
Labels: duplicate
