### ISSUE TITLE
Make Matrix4f element-fields "mxy" public like in Matrix3f

### ISSUE THREAD

**Issue by neo-expert** [JOML-CI/JOML#324] opened 2022-12-19 11:33 UTC
Why are the Matrix3f element-fields publicly accessible, and Matrix4f have only package-private visibility? It would be nice to have, to access them in Matrix4f without Method invocation too.

**Comment by httpdigest** [comment] 2022-12-19 11:38
Duplicate of #167, #156, #130

**Closed by httpdigest** 2022-12-19 11:38 UTC
