### ISSUE TITLE
Illegal Reflective Access

### ISSUE THREAD

**Issue by gudenau** [JOML-CI/JOML#141] opened 2017-10-28 21:47 UTC
While working on an engine I had this print to stderr.

Line of code causing the issue:
```
Matrix4f projection = new Matrix4f().perspective((float)Math.toRadians(45), ((float)window.getWidth())/window.getHeight(), 0.1f, 100.f);
```

Messages:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.joml.MemUtil$MemUtilUnsafe (file:/C:/Users/gudenau/.m2/repository/org/joml/joml/1.9.4/joml-1.9.4.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of org.joml.MemUtil$MemUtilUnsafe
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Edit:
Seems to be ```MemUtil.INSTANCE.zero(this);``` in ```org.joml.Matrix4f``` on line 4254.

**Comment by httpdigest** [comment] 2017-10-28 21:53
Duplicate of: https://github.com/JOML-CI/JOML/issues/138

**Closed by httpdigest** 2017-10-28 21:53 UTC

**Comment by gudenau** [comment] 2017-10-28 21:57
Sorry, I did not notice since 1.9.4 appeared to be the latest version and I did not see an issue.

**Comment by httpdigest** [comment] 2017-10-28 21:58
No prob. Will release 1.9.5 soon.

**Comment by httpdigest** [comment] 2017-10-31 19:54
FYI: [JOML 1.9.6](https://github.com/JOML-CI/JOML/releases/tag/1.9.6) has just been released. It solves this Java 9 issue. You can get it from GitHub Release page or from Maven Central.
