### ISSUE TITLE
JOML Warning: An illegal reflective access operation has occurred under Java 10.0.1

### ISSUE THREAD

**Issue by AwfulMint** [JOML-CI/JOML#163] opened 2018-05-15 22:34 UTC
So I decided to report this little one, my engine stills up and running but in startup I receive this anoying warnings.

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.joml.internal.MemUtil$MemUtilUnsafe (file:/C:/Users/luxxo/.m2/repository/org/joml/joml/1.9.8/joml-1.9.8.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of org.joml.internal.MemUtil$MemUtilUnsafe
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**Comment by httpdigest** [comment] 2018-05-16 04:29
Duplicate of https://github.com/JOML-CI/JOML/issues/158

**Closed by httpdigest** 2018-05-16 04:29 UTC
