### ISSUE TITLE
Intersectionf.testObOb - unclear

### ISSUE THREAD

**Issue by R0Zen** [JOML-CI/JOML#129] opened 2017-08-26 23:18 UTC
I was trying to use this function to test 2 boxs collide with each other on angle of 45 deg.
and seems like I doing something wrong.
this is the function I made to use the testObOb
 
as I found out I need to get 3 column from the rotation matrix of each object.
I tried passing the rotation vector (0, toRad(45), 0) for both boxes.
and got strange behaviors.
**I think that my issue is with the unit vectors but the thing is that I don't how to get them**.
so I did the following:

> 	public static boolean testObOb(Vector3f locA, Vector3f sizA, Vector3f rotA, Vector3f locB, Vector3f sizB, Vector3f rotB)
	{
		Matrix3f rot = new Matrix3f();
		rot.rotateXYZ(rotA);
		Vector3f xunitA = new Vector3f();
		Vector3f yunitA = new Vector3f();
		Vector3f zunitA = new Vector3f();
		rot.getColumn(0, xunitA);
		rot.getColumn(1, yunitA);
		rot.getColumn(2, zunitA);
		rot.identity();
		rot.rotateXYZ(rotB);
		Vector3f xunitB = new Vector3f();
		Vector3f yunitB = new Vector3f();
		Vector3f zunitB = new Vector3f();
		rot.getColumn(0, xunitB);
		rot.getColumn(1, yunitB);
		rot.getColumn(2, zunitB);
		Vector3f hsA= new Vector3f(sizA.x/2,sizA.y/2,sizA.z/2);
		Vector3f hsB= new Vector3f(sizB.x/2,sizB.y/2,sizB.z/2);
		return Intersectionf.testObOb(locA, xunitA, yunitA, zunitA, hsA, locB, xunitB, yunitB, zunitB, hsB);
	}

can someone point out what I did wrong?

**Comment by httpdigest** [comment] 2017-08-28 10:11
That method looks good and I also cannot reproduce "strange behaviors" with the Intersectionf.testObOb() method.
What exact results are you expecting vs. what exact results are you getting?
Please provide an executable code example (with concrete input values/arguments and expected outputs) that verifies your problem.

For example, here is a unit test that checks collision between two 45° rotated boxes:
```Java
public static void testObOb() {
	Vector3f c0 = new Vector3f();
	float EPSILON = 1E-5f;
	/* Position the second box so that they "almost" intersect */
	Vector3f c1 = new Vector3f((float)Math.sqrt(2) * 2 + EPSILON, 0, 0);
	Matrix3f m = new Matrix3f().rotateXYZ(0, (float) Math.toRadians(45.0), 0);
	Vector3f ux0 = m.getColumn(0, new Vector3f());
	Vector3f uy0 = m.getColumn(1, new Vector3f());
	Vector3f uz0 = m.getColumn(2, new Vector3f());
	Vector3f ux1 = m.getColumn(0, new Vector3f());
	Vector3f uy1 = m.getColumn(1, new Vector3f());
	Vector3f uz1 = m.getColumn(2, new Vector3f());
	Vector3f hs = new Vector3f(1);
	boolean intersects = Intersectionf.testObOb(c0, ux0, uy0, uz0, hs, c1, ux1, uy1, uz1, hs);
	assertFalse(intersects); // <- they do not intersect
	/* Position the second box so that they do intersect */
	c1 = new Vector3f((float)Math.sqrt(2) * 2 - EPSILON, 0, 0);
	m = new Matrix3f().rotateXYZ(0, (float) Math.toRadians(45.0), 0);
	ux0 = m.getColumn(0, new Vector3f());
	uy0 = m.getColumn(1, new Vector3f());
	uz0 = m.getColumn(2, new Vector3f());
	ux1 = m.getColumn(0, new Vector3f());
	uy1 = m.getColumn(1, new Vector3f());
	uz1 = m.getColumn(2, new Vector3f());
	hs = new Vector3f(1);
	intersects = Intersectionf.testObOb(c0, ux0, uy0, uz0, hs, c1, ux1, uy1, uz1, hs);
	assertTrue(intersects); // <- they do intersect
}
```

**Comment by R0Zen** [comment] 2017-08-28 11:28
![bad art work](https://user-images.githubusercontent.com/13879736/29771217-5c258c2c-8bfb-11e7-9681-31494ce676e9.png)

first of all sorry for the bad art work, didn't used Wacom for a long time.
the test that I made is trying to slide over the edges of 2 boxes.
the first is my character that is (1,4,1) in and just another box that is (4,4,4) in scale.
while if I using rotation (0,0,0) for both boxes the collision works great just like with the testAAB function.
but when I try to rotate the second box and the and first one with the angle of 45 deg on the Y axis just so they could slide on each others edge the collision works like none of them was rotated and even if I try to rotate 90 deg that should be the same as 0 deg because it's just a box the collision breaks in a manner that it reports for collision very far from the original object at all. 

here is the main code for the collision testing in the player's class:

> 		float angle = (float) Math.toRadians(45.0);
		Vector3f A_scale = new Vector3f( 1, 4, 1);
		Vector3f B_scale = new Vector3f( 4, 4, 4);
		Vector3f A_rot = new Vector3f( 0, angle, 0);
		Vector3f B_rot = new Vector3f( 0, angle, 0);
		Vector3f B_location = new Vector3f(-10,0,0);
		
		if (!CollisionCheacker.testObOb(player_location.add(motion_direction_x.mul(player_velocity)) , A_scale, A_rot, B_location, B_scale, B_rot))
		{
			// can move
		}

and here is the function in the CollisionCheacker class that using JOML function:

> 	public static boolean testObOb(Vector3f locA, Vector3f sizA, Vector3f rotA, Vector3f locB, Vector3f sizB, Vector3f rotB)
	{
		Matrix3f rot = new Matrix3f();
		rot.rotateXYZ(rotA);
		Vector3f xunitA = new Vector3f();
		Vector3f yunitA = new Vector3f();
		Vector3f zunitA = new Vector3f();
		rot.getColumn(0, xunitA);
		rot.getColumn(1, yunitA);
		rot.getColumn(2, zunitA);
		rot.identity();
		rot.rotateXYZ(rotB);
		Vector3f xunitB = new Vector3f();
		Vector3f yunitB = new Vector3f();
		Vector3f zunitB = new Vector3f();
		rot.getColumn(0, xunitB);
		rot.getColumn(1, yunitB);
		rot.getColumn(2, zunitB);
		Vector3f hsA= new Vector3f(sizA.x/2,sizA.y/2,sizA.z/2);
		Vector3f hsB= new Vector3f(sizB.x/2,sizB.y/2,sizB.z/2);
		return Intersectionf.testObOb(locA, xunitA, yunitA, zunitA, hsA, locB, xunitB, yunitB, zunitB, hsB);
	}

**Comment by httpdigest** [comment] 2017-08-28 11:44
> What exact results are you expecting vs. what exact results are you getting?
Please provide an executable code example (with concrete input values/arguments and expected outputs) that verifies your problem.

I cannot reproduce anything meaningful unless you provide a self-contained executable example (preferably in the form of a unit test/main method). An image is not an executable self-contained example.

**Comment by httpdigest** [comment] 2017-08-28 12:00
Here is yet another unit test with your case of two boxes sliding on each other with a 45 angle degree:
```Java
public static void testObOb45Slide() {
	Vector3f c0 = new Vector3f();
	float EPSILON = 1E-5f;
	/* Position the second box right over the first one so that they "almost" intersect/slide */
	// 2a^2 = c^2 = (1+0.5)^2 <-- length of a (box A + box B) squared
	// a^2 = (1+0.5)^2/2 -> a = sqrt(1.5)/sqrt(2)
	float a = (float)(1.5/Math.sqrt(2));
	Vector3f c1 = new Vector3f(a + EPSILON, a + EPSILON, 0);
	Matrix3f m = new Matrix3f().rotateXYZ(0, 0, (float) Math.toRadians(45.0));
	Vector3f ux0 = m.getColumn(0, new Vector3f());
	Vector3f uy0 = m.getColumn(1, new Vector3f());
	Vector3f uz0 = m.getColumn(2, new Vector3f());
	Vector3f ux1 = m.getColumn(0, new Vector3f());
	Vector3f uy1 = m.getColumn(1, new Vector3f());
	Vector3f uz1 = m.getColumn(2, new Vector3f());
	Vector3f hs0 = new Vector3f(1);
	Vector3f hs1 = new Vector3f(0.5f);
	boolean intersects = Intersectionf.testObOb(c0, ux0, uy0, uz0, hs0, c1, ux1, uy1, uz1, hs1);
	assertFalse(intersects); // <- they do not intersect
	c1 = new Vector3f(a - EPSILON, a - EPSILON, 0);
	intersects = Intersectionf.testObOb(c0, ux0, uy0, uz0, hs0, c1, ux1, uy1, uz1, hs1);
	assertTrue(intersects); // <- they do intersect
}
```

**Comment by R0Zen** [comment] 2017-08-28 12:35
here is all the data you need to reproduce my bug:
as you can see I'm inside the other object and the system reports false.
you can see all the data that you need in the console.
![image](https://user-images.githubusercontent.com/13879736/29773496-6e19409e-8c06-11e7-9be1-13214a48a68c.png)

**Comment by httpdigest** [comment] 2017-08-28 14:41
After digging into it a little bit more, it turned out that there was indeed a bug. Wrong conversion of the matrix indices when implementing the method from the book.
It should now be resolved with commit https://github.com/JOML-CI/JOML/commit/63754adbf3d598e44142aef63b01bb54e798f011.
Could you please try it out?

Thanks for reporting!

**Comment by httpdigest** [comment] 2017-08-28 14:45
You could also "workaround" the issue by either transposing the rotation matrix that you build in your method or obtaining the rows instead of the columns.

**Comment by R0Zen** [comment] 2017-08-28 15:05
oh thanks, I will check it soon.
btw thanks for the fast fix, your library is an excellent contribution for LWJGL keep the great work improving it 👍

**Comment by R0Zen** [comment] 2017-08-28 15:41
seems like it's work for one angle and for the other angle it's reports infinite collision.
you can see the debug and some of the code in this video: 
https://www.youtube.com/watch?v=NrEadrSTHhc

if it's still 360p give it a bit of time, I just uploaded it and it should be 1080p so you could see the debug data.

**Comment by httpdigest** [comment] 2017-08-28 18:16
Indeed. I am about to completely rewrite that method. Something must have gone wrong when porting it from the book and my silly tests did not catch that. :)

**Comment by httpdigest** [comment] 2017-08-28 18:37
Okay, got it working. Also used a separate interactive visual debugging program with all sorts of possible rectangle sizes and rotation angles. Seems to work now. Will tidy up and commit soon.

**Comment by R0Zen** [comment] 2017-08-28 19:02
great drop it when ready and I will give it a run.

**Comment by httpdigest** [comment] 2017-08-28 19:03
It's in. See the commit annotation above for c312304

**Comment by R0Zen** [comment] 2017-08-28 19:15
Ok, it works as expected now.
tested it few tiimes with few box sizes.
 👍 👍 👍

**Closed** 2017-08-28 20:26 UTC
Labels: bug
